import type { BlogArticle } from "./types";
import { article as a0 } from "./articles/assistante-virtuelle-charente-tpe";
import { article as a1 } from "./articles/secretaire-independante-angouleme-ou-recrutement";
import { article as a2 } from "./articles/externalisation-administrative-charente-guide-dirigeant";
import { article as a3 } from "./articles/gestion-administrative-tpe-angouleme-erreurs";
import { article as a4 } from "./articles/automatisation-ia-pme-charente-par-ou-commencer";
import { article as a5 } from "./articles/aide-administrative-artisan-cognac";
import { article as a6 } from "./articles/assistante-administrative-distance-comment-ca-marche";
import { article as a7 } from "./articles/assistante-independante-sur-place-ou-distance";
import { article as a8 } from "./articles/deleguer-administratif-artisan-mode-emploi";
import { article as a9 } from "./articles/assistante-freelance-tpe-ou-salariee";
import { article as a10 } from "./articles/facturation-electronique-2026-tpe";
import { article as a11 } from "./articles/facture-electronique-artisan-guide-simple";
import { article as a12 } from "./articles/pdf-email-facture-electronique";
import { article as a13 } from "./articles/facturation-electronique-micro-entrepreneur";
import { article as a14 } from "./articles/choisir-plateforme-facturation-agreee";
import { article as a15 } from "./articles/factur-x-ubl-cii-explication-simple";
import { article as a16 } from "./articles/calendrier-facturation-electronique";
import { article as a17 } from "./articles/risques-si-pas-pret-facturation-electronique";
import { article as a18 } from "./articles/se-preparer-facturation-electronique-5-etapes";
import { article as a19 } from "./articles/facturation-electronique-expert-comptable-qui-fait-quoi";
import { article as a20 } from "./articles/temps-administratif-dirigeant-tpe";
import { article as a21 } from "./articles/arreter-paperasse-dimanche-soir";
import { article as a22 } from "./articles/circuit-devis-facture-relance";
import { article as a23 } from "./articles/classement-documents-entreprise-simple";
import { article as a24 } from "./articles/echeances-urssaf-tva-assurances";
import { article as a25 } from "./articles/charge-mentale-dirigeant-administratif";
import { article as a26 } from "./articles/preparer-pieces-comptables-fil-de-leau";
import { article as a27 } from "./articles/quelles-taches-deleguer-dirigeant";
import { article as a28 } from "./articles/organiser-gestion-creation-entreprise";
import { article as a29 } from "./articles/reorganiser-gestion-administrative-entreprise";
import { article as a30 } from "./articles/tableau-de-bord-tresorerie-tpe";
import { article as a31 } from "./articles/creneau-administratif-hebdomadaire";
import { article as a32 } from "./articles/automatiser-relances-factures";
import { article as a33 } from "./articles/reponse-automatique-email-entreprise";
import { article as a34 } from "./articles/assistant-ia-tpe-utilite";
import { article as a35 } from "./articles/automatiser-desordre-gestion-entreprise";
import { article as a36 } from "./articles/taches-a-automatiser-tpe";
import { article as a37 } from "./articles/ia-pour-artisans-exemples-concrets";
import { article as a38 } from "./articles/prise-rendez-vous-en-ligne-temps-gagne";
import { article as a39 } from "./articles/trier-emails-automatiquement";
import { article as a40 } from "./articles/gain-temps-automatisation-entreprise";
import { article as a41 } from "./articles/ia-remplace-assistante";
import { article as a42 } from "./articles/relance-facture-impayee";
import { article as a43 } from "./articles/delais-paiement-professionnels";
import { article as a44 } from "./articles/pre-comptabilite-definition";
import { article as a45 } from "./articles/reduire-honoraires-expert-comptable";
import { article as a46 } from "./articles/suivre-tresorerie-petite-entreprise";
import { article as a47 } from "./articles/envoyer-devis-rapidement";
import { article as a48 } from "./articles/gerer-factures-fournisseurs";
import { article as a49 } from "./articles/indicateurs-gestion-tpe";
import { article as a50 } from "./articles/externaliser-pre-comptabilite";
import { article as a51 } from "./articles/preparer-cloture-comptable-tpe";
import { article as a52 } from "./articles/cout-assistante-freelance-vs-salariee";
import { article as a53 } from "./articles/externaliser-administratif-sans-perdre-controle";
import { article as a54 } from "./articles/confidentialite-externalisation-administrative";
import { article as a55 } from "./articles/petite-mission-assistante-independante";
import { article as a56 } from "./articles/directrice-operations-externalisee-role";
import { article as a57 } from "./articles/quand-deleguer-administratif";
import { article as a58 } from "./articles/collaboration-assistante-distance-semaine-type";
import { article as a59 } from "./articles/tarif-assistante-administrative-independante-facteurs";
import { article as a60 } from "./articles/gestion-administrative-artisan-batiment";
import { article as a61 } from "./articles/assistante-administrative-courtier";
import { article as a62 } from "./articles/assistant-administratif-gestion-patrimoine";
import { article as a63 } from "./articles/gestion-administrative-praticien-bien-etre";
import { article as a64 } from "./articles/administratif-freelance-tech";
import { article as a65 } from "./articles/facturation-recurrente-consultant";
import { article as a66 } from "./articles/gestion-administrative-commercant";
import { article as a67 } from "./articles/assistante-administrative-profession-liberale";
import { article as a68 } from "./articles/passage-micro-entreprise-societe-gestion";
import { article as a69 } from "./articles/gestion-entreprise-familiale-couple";
import { article as a70 } from "./articles/telesecretariat-charente";
import { article as a71 } from "./articles/tarif-secretaire-independante-2026";

export const blogArticles: BlogArticle[] = [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71];

export const blogCategories = Array.from(new Set(blogArticles.map((article) => article.category)));

export function getBlogArticle(slug: string) {
  return blogArticles.find((article) => article.slug === slug);
}

export { formatArticleDate, readingMinutes } from "./types";
export type { BlogArticle, BlogFaqItem, BlogImage, BlogSection } from "./types";
